### PR TITLE
On boarding information for Xudong Tang

### PR DESCRIPTION
**Pull request by XudongTang**
This is my onboarding information. I put my info in a .md file. I also included a .jpg file of my photo.

### CODE REVIEW

**Comment by crsl4** [comment]
Hi @XudongTang , you created a new file with your information, but you should add yourself to the existing `assets/people.md` file.

**Review by crsl4 — CHANGES_REQUESTED** [review]
Hi Xudong, you need to add yourself to the existing `assets/people.md` file instead of creating a new file.

**Comment by XudongTang** [comment]
Sorry for the mistake, I didn't check the files through...I did not find people.md in /assets, but I found it in /pages (I think this is the target file). I added my information in the same format as others and uploaded my photo in /assets/pics. Hopefully, I did those things correctly this time, but let me know if I need to make any changes!

**Comment by crsl4** [comment]
ah yes! sorry, my bad! It is in pages, yes!

**Review by crsl4 — APPROVED** [review]

**Pull request merged**
